//
// Created by John on 12-Oct-16.
//

#ifndef TRAVELING_SALESMAN_PROBLEM_SALESMANPROBLEM_H
#define TRAVELING_SALESMAN_PROBLEM_SALESMANPROBLEM_H


class SalesmanProblem {

};


#endif //TRAVELING_SALESMAN_PROBLEM_SALESMANPROBLEM_H
